<?php
namespace app\common\controller;
use think\Controller;
class Base extends Controller
{
    public static $ADMIN_INDEX_URL='admin/index/index';
    public static $ADMIN_LOGIN_URL='admin/publics/login';
   protected function initialize()
   {
       parent::initialize(); // TODO: Change the autogenerated stub
   }
}
